[package]
name = "cmaze"
version = "0.6.0"
edition = "2021"
description = "Core of tmaze game"
license-file = "../LICENSE"
readme = "../README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "^0.8.5"
thiserror = "1.0.31"
pausable_clock = "^1.0.1"
crossbeam = "^0.8.1"
rayon = "^1.6.0"
hashbrown = { version = "0.13.2", optional = true }

[dev-dependencies]
criterion = "0.4.0"

[features]
hashbrown = ["dep:hashbrown"]

[[bench]]
name = "kruskals"
harness = false
