[package]
name = "cmaze"
version = "0.7.2"
edition = "2021"
description = "Core of tmaze game"
license-file = "../LICENSE"
readme = "../README.md"
repository = "https://github.com/ur-fault/tmaze"

[dependencies]
rand = "^0.8.5"
thiserror = "1.0.31"
pausable_clock = "^1.0.1"
rayon = "^1.6.0"
hashbrown = { version = "0.14", optional = true }
log = "0.4"
serde = { version = "^1", features = ["derive"] }

[dev-dependencies]
criterion = "0.5"

[features]
hashbrown = ["dep:hashbrown"]

[[bench]]
name = "kruskals"
harness = false
