[package]
name = "cmaze"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "^0.8.5"
rayon = "^1.5.3"
thiserror = "1.0.31"
pausable_clock = "^1.0.1"
crossbeam = "^0.8.1"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "kruskals"
harness = false