[package]
name = "tmaze"
version = "1.8.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "^2"
crossterm = {version = "^0.24.0", features = ["serde"]}
masof = {git = "https://github.com/MineFuf/masof.git"}
substring = "^1.4.5"
serde = {version = "^1.0.136", features = ["derive"]}
pausable_clock = "^1.0.1"
dirs = "^4.0.0"
ron = "0.8.0"
clap = { version = "4.0.29", features = ["derive"] }
cmaze = { path = "../cmaze"}
pad = "0.1.6"